### ISSUE TITLE
Если убрать "Доступ в любое время" из прав токена, то он истечет через некоторое время и его нужно будет обновить

### ISSUE THREAD

**Issue by evtn** [nitreojs/vk-cover-spotify-playback#2]

**Comment by nitreojs** [comment]
- [ ] действительно
- [x] и правда
- [ ] что то здесь не так
- [ ] что делать будем
- [ ] как убрать этот список
- [x] я хз

**Comment by bit0r1n** [comment]
жалк

**Comment by evtn** [comment]
Ребята это не смешно вот что смешно

Мать собирает сына в школу. Кладёт хлеб колбасу и гвозди:
— Вот, берешь хлеб, кладёшь на него колбасу и ешь.
— А гвозди?
— Так вот же они!

**Comment by nitreojs** [comment]
друзья как оказалось он неправильно прочитал ридми и подумал о чем то другом короче Просмотры хентая с трапами не доводят до добра. Сначала возникает неприязнь, но позже
интерес берёт вверх и ты уже жить не можешь не подрочив хотя бы раз на сие чудо.
Вот и меня это не довело до добра. Смотря хентай с трапами ежедневно по нескольку раз в день я стал мечтать переодеть милого мальчика из тиктока в костюм горничной и жестко выебать его. И не просто жестко выебать, а что бы прям с дерьмом, зрителями, избиениями и тому прочим.
Однажды мое желание заставило меня продумывать как это будет, и я придумал. Для начала мне нужно было накачаться и увеличить член с шестнадцати до двадцати. Так мой отец чиновник, второе было сделать не так уж и сложно, а вот с горой мышц были проблемы. Так как я был жирным уебком, хоть и высоким (193см). Мне пришлось потратить три с половиной года что бы стать жестким любителем железа. Комьюнити у любителей железа на удивление очень приятное. На стояки на друг друга никто не обращает, только лампово шутит и сразу же приступают крутить штангу на хую.

**Comment by evtn** [comment]
Hello

Please release this for Macos

**Comment by nitreojs** [comment]
hello no
